name: docs
on: [push]
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏èIvy Robot
        uses: actions/checkout@v2
        with:
          path: ivy_robot
          persist-credentials: false

      - name: Build Docs
        run: |
          cd ivy_robot
          docker run --rm -v "$(pwd)":/project unifyai/doc-builder:latest

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ivy_robot/docs/build
          CLEAN: false
          GIT_CONFIG_NAME: ivy-seed
          GIT_CONFIG_EMAIL: ivydl.team@gmail.com
