name: tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸Ivy Robot
        uses: actions/checkout@v2
        with:
          path: ivy_robot
          persist-credentials: false

      - name: Run Tests
        run: |
          docker run --rm -v `pwd`/ivy_robot:/ivy_robot ivydl/ivy-robot:latest python3 -m pytest ivy_robot_tests/
